name: Build & Deploy

on:
  push:
    branches: [ main ]
    paths:
      - postgres/**


jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - uses: mr-smithers-excellent/docker-build-push@v5
        name: Build & push Docker image
        with:
          dockerfile: ./postgres/Dockerfile
          directory: ./postgres
          image: fiitteam8/postgres_db
          tags: endpoints, latest
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
